Add document for 'Why learn Zsh'
sforzando/EmployeeTraining pull request #2
Opened 2020-08-10 05:39 UTC by tomoya-sforzando

## Describe the PR

To close #1 .

## Detail of the change

Add `WhyLearnZsh.md`.
Export PDF with Marp( on Extension of Visual Studio Code).

## Anticipated impacts

None.

## Additional context

Add any other context about the problem here.

2020-08-10 09:06 UTC, shin-sforzando requested changes
Marp使うなら、README.mdのRequirements章にMarpを足すなどしてください。

2020-08-10 11:54 UTC, tomoya-sforzando commented
@shin-sforzando README.mdに追記しました。

2020-08-10 13:55 UTC, shin-sforzando requested changes
MarpはCLIもあるので、生成物の `pdf` をGit管理下におかず、むしろGitHub Actions等で生成しては？

2020-08-10 13:55 UTC, shin-sforzando commented on src/WhyLearnZsh.md
> +  - 100個のフォルダを用意し、それぞれ`AAA`, `AAB`,,`ABA`, `ABB`,,のフォルダ名が付けられている
句読点の数おかしい。

2020-08-10 13:55 UTC, shin-sforzando commented on src/WhyLearnZsh.md
> +- ↑ さらに、GUIアプリケーションよりCLIの方が効率的な作業ができるケースがあるため
↑から始まる行は1インデント低いのでは？

2020-08-10 13:55 UTC, shin-sforzando commented on src/WhyLearnZsh.md
> +**iTerm2**
Marpは `#### iTerm2` は使えないんですか？

2020-08-25 09:07 UTC, shin-sforzando requested changes

2020-08-25 09:07 UTC, shin-sforzando commented on src/WhyLearnZsh.md
> +  - `AAA` のフォルダには `AAA-00000.txt` ,,, `AAA-00099.txt` という名前のファイルが入っている
https://ja.wikipedia.org/wiki/リーダー_(記号)

2020-08-25 09:07 UTC, shin-sforzando commented on README.md
> +1. Open Markdown File with Visual Studio Code.
箇条書きの末尾にはピリオド要りません。

2020-08-25 09:07 UTC, shin-sforzando commented on src/WhyLearnZsh.md
> +- ↑ さらに、GUIアプリケーションよりCLIの方が効率的な作業ができるケースがあるため
【再掲】↑から始まる行は1インデント低いのでは？

2020-08-25 09:07 UTC, shin-sforzando commented on src/WhyLearnZsh.md
> +- コマンド履歴を一覧し、そこから実行する
本文とリストの間に空行が必要。
cf. http://nanoappli.com/blog/archives/7898

2020-09-03 06:34 UTC, tomoya-sforzando commented on src/WhyLearnZsh.md
> +  - `AAA` のフォルダには `AAA-00000.txt` ,,, `AAA-00099.txt` という名前のファイルが入っている
三点リーダー使います

2020-09-03 19:13 UTC, shin-sforzando requested changes

2020-09-03 19:13 UTC, shin-sforzando commented on README.md
> +1. Open Markdown File with Visual Studio Code.
だから、箇条書きの末尾にはピリオドいらないって。

cf. https://guides.github.com/features/mastering-markdown/

2020-09-03 19:13 UTC, shin-sforzando commented on src/WhyLearnZsh.md
> +  - `$ git commit` など自動的に開かれるエディタを設定しておく
`git` のためのエディタは `~/.gitconfig` の `core.editor` で設定するべき。
cf. https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA-Git-%E3%81%AE%E8%A8%AD%E5%AE%9A

2020-09-03 19:40 UTC, tomoya-sforzando commented on src/WhyLearnZsh.md
> +  - `$ git commit` など自動的に開かれるエディタを設定しておく
>`$ git commit` など自動的に開かれるエディタを設定しておく

は消して、 `git` のためのエディタについては、 GitHub Flowの資料の方で追記することにします。

2020-09-04 09:14 UTC, shin-sforzando approved these changes

2020-09-04 09:15 UTC, merged